name: Release

on:
  push:
    branches:
      - master
jobs:
  push-to-registry:
    strategy:
      fail-fast: true
      matrix:
        version: ["7.4", "8.0", "8.1"]

    env:
      VERSION: ${{ matrix.version }}

    name: release-${{ matrix.version }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "all"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
           docker buildx create --name php
           docker buildx use php
           make release
